config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 35253091576722 # Put your project id here

profile: default # Put your profile here

model-paths: ["models"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

# Adding flags section to address behavior change warnings
flags:
  require_yaml_configuration_for_mf_time_spines: true

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
